apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-git-nfs
  namespace: airflow
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi